#!/bin/bash
# dunst notification control script

case "$1" in
start)
   dunst -config ~/.config/i3/dunst/dunstrc &
   ;;
stop)
   pkill -x dunst
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ "$(pidof -x dunst)" ]; then
     echo "$0 is running"
   else
     echo "$0 is stopped"
     exit 1
   fi
   ;;
notify)
   notify-send -u critical "Test message: critical test 1"
   notify-send -u normal "Test message: normal test 2"
   notify-send -u low "Test message: low test 3"
   notify-send -u critical "Test message: critical test 4"
   notify-send -u normal "Test message: normal test 5"
   notify-send -u low "Test message: low test 6"
   notify-send -u critical "Test message: critical test 7"
   notify-send -u normal "Test message: normal test 8"
   notify-send -u low "Test message: low test 9"
   ;;
*)
   echo "Usage: $0 {start|stop|restart|status|notify}"
esac

exit 0
