#!/bin/bash
set -x

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  sudo systemctl start firewalld.service
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  sudo systemctl restart firewalld.service
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  sudo systemctl stop firewalld.service
fi

status=$(systemctl is-active firewalld.service)

if [[ $? -gt 0 ]]; then
  exit
fi

if [[ "${status}" != "inactive" ]]; then
  echo "on"
  echo "on"
  echo ""
else
  echo "off"
  echo "off"
  echo ""
fi
