#!/bin/sh
xrandr --output VIRTUAL1 --off --output DP1 --off  --output DP2-3 --off --output HDMI2 --off --output HDMI1 --off --output VGA1 --off --output DP2 --off
xrandr --output eDP1 --primary --mode 1600x900 --pos 1680x0 --rotate normal
xrandr --output DP2-1 --mode 1360x768 --pos 3280x0 --rotate normal
xrandr --output DP2-2 --mode 1680x1050 --pos 0x0 --rotate normal
