#!/bin/sh
#
# Only primary screen configuration setup
#
xrandr --output HDMI2 --off --output HDMI1 --off --output VGA1
xrandr --output DP1 --off --output DP2 --off --output DP2-1 --off --output DP2-2 --off --output DP2-3 --off
xrandr --output VIRTUAL1 --off --output eDP1 --primary --auto --pos 0x0 --rotate normal
